### ISSUE TITLE
Python API to metrics_ops is not working in pip package 1.4.3

### ISSUE THREAD

**Issue by zhejz** [waymo-research/waymo-open-dataset#425]
The python API `py_metrics_ops.py` for computing metrics seems to be broken in the latest (1.4.3) pip package.

To reproduce:
Make a new environment
```
conda create -n test python=3.9
conda activate test
pip3 install --upgrade pip
pip3 install waymo-open-dataset-tf-2-6-0==1.4.3
```
Run in python
```
from waymo_open_dataset.metrics.ops import py_metrics_ops
py_metrics_ops.metrics_module.motion_metrics
```
The following error will show up
```
AttributeError: module '012ff3e36e3c24aefc4a3a7b68a03fedd1e7a7e1' has no attribute 'motion_metrics'
```
Presumably the `metrics_ops.so` is not correctly built or loaded. Or maybe some API have changed? Other pip versions, like 1.4.1,  do not have this problem.

**Comment by alexgorban** [comment]
`motion_metrics` is a function of the `py_metrics_ops` module ([source code](https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/metrics/ops/py_metrics_ops.py#L57))

**Comment by zhejz** [comment]
The `motion_metrics` function is a python wrapper of `metrics_module.motion_metrics` in [line 78](https://github.com/waymo-research/waymo-open-dataset/blob/1297cdcbcd103d4befb4b498e50a0c030053e6c0/waymo_open_dataset/metrics/ops/py_metrics_ops.py#L78). And this `metrics_module` has no attribute `motion_metrics`.

**Comment by sephyli** [comment]
I had the same problem when calling `metrics_module.detection_metrics`. 
My version of pip package is 1.4.3 with tf 2.6.0.
I don't see the interface changed in metrics_ops.cc, it seems that `metrics_ops.so` is not correctly built.
Change to version 1.4.1 will fix this.

**Comment by hanklin3** [comment]
+1 same issue with waymo-open-dataset-tf-2-6-0==1.4.3
running the tutorial
https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_motion.ipynb
tried 1.4.1 seems will fix it
